name = "qdt"
version = "0.1.0"
defaultTargets = ["qdt"]
testDriver = "QdtTest"
license = "Apache-2.0"
description = "Query-based Dependent Type Elaborator"

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"

[[require]]
name = "FSWatch"
git = "https://github.com/intgrah/lean-fswatch"
rev = "master"

[[lean_lib]]
name = "Qdt"

[[lean_lib]]
name = "QdtTest"
globs = ["QdtTest.+"]

[[lean_exe]]
name = "qdt"
root = "Main"
